name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-linux:
    name: Build for Linux (x86_64)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binary
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-api-linux
          path: target/release/mobile-api

  build-windows:
    name: Build for Windows (x86_64)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binary
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-api-windows
          path: target/release/mobile-api.exe

  release:
    name: Create GitHub Release
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: rust-api-linux
          path: ./linux

      - uses: actions/download-artifact@v4
        with:
          name: rust-api-windows
          path: ./windows

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            linux/mobile-api
            windows/mobile-api.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
