name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-linux:
    name: Build for Linux (x86_64)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binary
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobile-backend-linux
          path: target/release/mobile-backend

  build-windows:
    name: Build for Windows (x86_64)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binary
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobile-backend-windows
          path: target/release/mobile-backend.exe

  release:
    name: Create GitHub Release
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: mobile-backend-linux
          path: ./linux

      - uses: actions/download-artifact@v4
        with:
          name: mobile-backend-windows
          path: ./windows

      - name: Create GitHub Release
      - run: |
          gh release create ${{ github.ref_name }} \
            ./linux/mobile-backend=mobile-backend-linux \
            ./windows/mobile-backend.exe=mobile-backend-windows \
            --title "Release ${{ github.ref_name }}" \
            --notes "This release includes binaries for both Linux and Windows."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
